### ISSUE TITLE
spacepy fortran compile problem (f2py) on python 3

### ISSUE THREAD

**Issue by letmaik** [esa/auromat#1]
From travis ci log:

```
Reading fortran codes...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/bin/f2py", line 26, in <module>
    main()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/numpy/f2py/f2py2e.py", line 650, in main
    run_main(sys.argv[1:])
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/numpy/f2py/f2py2e.py", line 408, in run_main
    postlist = callcrackfortran(files, options)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/numpy/f2py/crackfortran.py", line 3219, in crackfortran
    readfortrancode(files, crackline)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/numpy/f2py/crackfortran.py", line 365, in readfortrancode
    l = fin.readline()
  File "/opt/python/3.4.2/lib/python3.4/fileinput.py", line 363, in readline
    self._buffer = self._file.readlines(self._bufsize)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 2242: invalid start byte
Traceback (most recent call last):
  File "setup.py", line 831, in <module>
    setup(**setup_kwargs)
  File "/home/travis/miniconda2/envs/test/lib/python3.4/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/home/travis/miniconda2/envs/test/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda2/envs/test/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda2/envs/test/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/travis/miniconda2/envs/test/lib/python3.4/site-packages/numpy/distutils/command/install.py", line 60, in run
    r = old_install.run(self)
  File "/home/travis/miniconda2/envs/test/lib/python3.4/distutils/command/install.py", line 539, in run
    self.run_command('build')
  File "/home/travis/miniconda2/envs/test/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/travis/miniconda2/envs/test/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 639, in run
    self.compile_irbempy()
  File "setup.py", line 413, in compile_irbempy
    subprocess.check_call(cmd)
  File "/home/travis/miniconda2/envs/test/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['f2py', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1

The command "cd spacepy && python setup.py install && cd .." failed and exited with 1 during 
```

Not sure why this happens now, it worked in the past. Maybe there was a change in spacepy (since this is installed directly from git master).

**Comment by meresmclr** [comment]
Hello,
I would consider a few things

* Pythonic handling of prereq packages--using setup.py  `install_requires` without version numbers, remove requirements.txt
* refactor .travis.yml. I have used Travis extensively and there are builtins that handle some of what's being done manually
* use Ubuntu 14.04 in Travis.

If this is still a package of interest, I could fork and do this.

**Comment by letmaik** [comment]
Go ahead! Anyone with a profile picture like that has my approval :)

About your first point, if you remove version numbers, how would you make sure that the appropriate minimum versions are installed? Otherwise you would just get possibly confusing errors at runtime if there's no check at all at setup time.

**Comment by meresmclr** [comment]
https://packaging.python.org/requirements/#install-requires
handles version bounding within `setup.py` e.g. install_requires(['numpy>=1.6.1'])`

**Comment by letmaik** [comment]
Yeah exactly, that's why I was confused when you wrote "using setup.py install_requires without version numbers".

**Comment by meresmclr** [comment]
Yes I think I didn't read down far enough to see that you did have lower version bounds in `setup.py`.

**Comment by letmaik** [comment]
It's merged, thanks again! 👍
